[theme]
base = "light"
primaryColor = "#3F72BF"
backgroundColor = "#EEF4FB"
secondaryBackgroundColor = "#F8FBFF"
textColor = "#243956"
font = "sans serif"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false
